CONFIG_GPIO=y
CONFIG_PRINTK=y
CONFIG_I2C=y
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_SHELL=y
CONFIG_SHELL_BACKEND_SERIAL=y
CONFIG_SHELL_PROMPT_UART="envdaq_bot:~$ "
CONFIG_LOG=y
CONFIG_LOG_BACKEND_UART=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_THREAD_MONITOR=y
CONFIG_THREAD_NAME=y
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_THREAD_STACK_INFO=y
CONFIG_INIT_STACKS=y
CONFIG_STACK_SENTINEL=y
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048


CONFIG_RTC=y

# ADC support
CONFIG_ADC=y
CONFIG_ADC_ASYNC=y